### ISSUE TITLE
Broken with "hrun" and "detritus" if style=page

### ISSUE THREAD

**Issue by shadowdoc** [dokufreaks/plugin-filelist#11]
In Hrun $renderer->lastlevel is a protected variable and not accessible in Syntax.php line number 341

**Comment by LarsGit223** [comment]
The problem is also present on "Detritus".
It occurs if ```style=page``` is used.

The following causes a blank page which can not be edited anymore until the filelist plugin is disabled:

<code>{{filelist>lib/images/*&style=page&direct=1}}</code>

The same in list mode works fine:

<code>{{filelist>lib/images/*&style=list&direct=1}}</code>

**Comment by LarsGit223** [comment]
I did a change which at least prevents the error if ```style=page``` is used. In the case that you use "hrun" or newer a workaround will be used which means that the filelist plugin always uses header level 1.

If you use an older release than "hrun" then this will be detected now and ```$renderer->lastlevel``` will be used resulting in a correct output.

I placed a pull-request in DokuWiki to make $lastlevel accessible through a getter function/method, see https://github.com/splitbrain/dokuwiki/pull/1555. The issue can only finally be closed if that pull-request is merged. So for now, I leave it open.

**Comment by LarsGit223** [comment]
The pull-request has been merged and will be included in the next DokuWiki release. So I close this now.

**Comment by turnermm** [comment]
I've updated the plugin page to reflect the fix.  Please check.  Thanks.

**Comment by LarsGit223** [comment]
Looks good to me. Thanks.
