### ISSUE TITLE
Add "Created By" column

### ISSUE THREAD

**Issue by lpaulsen93** [dokufreaks/plugin-filelist#28]
This feature request was received on the dokufreaks mailing list on the 14.03.2018:

> Hi Freaks
> 
> Can you add a "Created by" column next to "Last modified". I know this feature is already available via the Media Manager where you can see who created the file in the History section but it would be awsome to have it implemented in filelist plugin.
> 
> Use case 1:
> 
> If using Media Manager to upload files then have an option in filelist plugin to display "created by" column. If true then it would read the USER who uploaded the fille. If file was uploaded not using Media Manager then "created by" column would read 'Root' or something similar.
> 
> Filename |  Filesize  | Last modified  |  Created by
> ------------|-----------|---------------------|----------------
> |  example.pdf |   20KiB     |     2018/03/14      |    Husam        |
> 
> Thank you for considering this feature.
> 
> Many Thanks
> 
> Husam
>

**Comment by HusGit87** [comment]
Hi Lars

It is always showing the creator as "unknown". I tested uploading documents and images via the Media Manager.

Regards
Hus

**Comment by LarsGit223** [comment]
Hi Hussam,

yes that's correct. It will actually only work if files have been uploaded via the media manager. Otherwise DokuWiki doesn't know which DokuWiki user created the file. It will also NOT work if the option ```direct=1``` is set. That means it only works using a wiki path not a filepath. Are you sure you re-installed the plugin? Could you post the filelist syntax you used?

Thanks,
Lars

**Comment by Klap-in** [comment]
Todo: add this option to the documentation

**Comment by splitbrain** [comment]
this no longer applies since the plugin no longer lists files within the wiki
