### ISSUE TITLE
Plugin not listenting files & when I use &recursive=1 show error

### ISSUE THREAD

**Issue by cmcastan** [dokufreaks/plugin-filelist#42]
Hi

This works properly in previos version

<searchtable>
<sortable>
{{filelist>:sandhar:rrhh:confidencial:archivo:trabajadores:oficiales:aeat:*.pdf&sort=mtime&style=table&recursive=1}}
</sortable>
</searchtable>

But now show 

dokuwiki\Exception\FatalException: Maximum execution time of 30 seconds exceeded
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the filelist plugin.

More info has been written to the DokuWiki error log.

error.log is:

2024-03-20 10:45:15     /var/www/html/lib/plugins/filelist/Crawler.php(71)      E_ERROR: Maximum execution time of 30 seconds exceeded
  #0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  #1 {main}
2024-03-20 10:45:16     /var/www/html/lib/plugins/filelist/Crawler.php(94)      E_ERROR: Maximum execution time of 30 seconds exceeded
  #0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  #1 {main}
2024-03-20 10:46:48     /var/www/html/lib/plugins/filelist/Crawler.php(71)      E_ERROR: Maximum execution time of 30 seconds exceeded

Any idea?

**Comment by KaiMartin** [comment]
The filelist plugin changes its syntax with the last update. The path is now supposed to be a 'real' path of the file system rather than a dokuwiki namespace. Consequently, colons do not work anymore. Additionally define an alias to a starting point of the path in the configuration of the plugin. 

In my local wiki I defined an alias for 'media' in the config:  
```
/var/www/elektroniq/data/media/
A>media
```
Where ''/var/www/...'' is the actual path of media in the file system of my server.  This is for Linux. For a Windows server you may need to swap the ''/'' to ''\''. 
With this definition, a list of all the files in the wiki name space looks like this:
```
{{filelist>media:wiki:*&style=list&recursive=1}}
```

**Comment by splitbrain** [comment]
This plugin should not be used to access media files or anything inside the wiki! This would circumvent ACLs and might compromise the security of the wiki. An update has been made to prevent miscofigurations like that.
